--KH계정을 만들고 그 비밀번호는 KH로 해주세요






CREATE TABLE STUDENT_TBL (
    STUDENT_NAME VARCHAR2(20),
    STUDENT_AGE NUMBER,
    STUDENT_GRADE NUMBER,
    STUDENT_ADDRESS VARCHAR2(100)
);

--TABLE에 데이터를 넣는 방법! ->회원가입
--뒤에 괄호(컬럼명)는 생략가능
INSERT INTO STUDENT_TBL (STUDENT_NAME, STUDENT_AGE, STUDENT_GRADE, STUDENT_ADDRESS)
VALUES('이용자', 55, 3, '서울시 종로구');
--괄호생략
INSERT INTO STUDENT_TBL VALUES(NULL, 33, 1, ' ');

--데이터를 삭제해보자! -> 회원탈퇴
DELETE FROM STUDENT_TBL
--딜리트 응용 무조건 딜리트프롬웨어로 외우기~~~
WHERE STUDENT_GRADE = 2;

--데이터를 수정해보자!
UPDATE STUDENT_TBL
SET STUDENT_NAME = '일용자';
--WHERE STUDENT_AGE = 22;
--WHERE절을 생략하면 다 바뀌어버림~!~!~

--수정 = 삭제+생성
--테이블 삭제
DROP TABLE STUDENT_TBL;

--데이터 조회
--웨어 생략 가능~!~!~!~!
SELECT STUDENT_NAME, STUDENT_ADDRESS
FROM STUDENT_TBL
WHERE STUDENT_GRADE = 2;

--CREATE문 어딧느지 모를때~
--describe
DESC DATATYPE_TBL;

INSERT INTO DATATYPE_TBL
VALUES('문자3', '문자열3', 44, SYSDATE, SYSTIMESTAMP);

SELECT MOONJJA, MOONJJAYUL, SOOJJA, NALJJA, NALJJA2
FROM DATATYPE_TBL;

--수정하고싶음~!~!~~!~
UPDATE DATATYPE_TBL
SET MOONJJA = '오라클'
WHERE SOOJJA = 33;

DELETE FROM DATATYPE_TBL
WHERE SOOJJA = 22;

CREATE TABLE DATATYPE_TBL (
    MOONJJA CHAR(10),
    --알파벳10글자, 한글 3글자
    MOONJJAYUL VARCHAR2(100),
    --알파벳100글자, 한글 33글자
    SOOJJA NUMBER,
    NALJJA DATE,
    NALJJA2 TIMESTAMP
);